-- Cadastro dos membros reais (só cupom por enquanto — nome provisório =
-- o próprio cupom, capitalizado, fácil de trocar depois pelo Table Editor
-- ou com: update members set name = 'Nome Real' where coupon_code = 'CUPOM';).
insert into members (name, coupon_code) values
  ('Allgayer', 'ALLGAYER'),
  ('Maou', 'MAOU'),
  ('Dark', 'DARK'),
  ('Kevyn', 'KEVYN'),
  ('Miyuki', 'MIYUKI'),
  ('Soso', 'SOSO'),
  ('Turra', 'TURRA'),
  ('Gihferraz', 'GIHFERRAZ'),
  ('Nephilim', 'NEPHILIM'),
  ('Ciprila', 'CIPRILA'),
  ('Bella', 'BELLA'),
  ('Maisa', 'MAISA'),
  ('Kazen', 'KAZEN'),
  ('Naan', 'NAAN'),
  ('Douug', 'DOUUG'),
  ('Errado', 'ERRADO'),
  ('Restivo', 'RESTIVO'),
  ('Xander', 'XANDER'),
  ('Obscure', 'OBSCURE'),
  ('Fredola', 'FREDOLA'),
  ('Under', 'UNDER'),
  ('Liano', 'LIANO'),
  ('Arihells', 'ARIHELLS'),
  ('Leal', 'LEAL'),
  ('Neon', 'NEON'),
  ('Alisonnxz', 'ALISONNXZ'),
  ('Tiago', 'TIAGO'),
  ('Ryandro', 'RYANDRO'),
  ('Fitduda', 'FITDUDA'),
  ('Rafa', 'RAFA'),
  ('Acne', 'ACNE'),
  ('Evy', 'EVY'),
  ('Ladymarie', 'LADYMARIE'),
  ('Paradise', 'PARADISE'),
  ('Vic', 'VIC'),
  ('Freitaz', 'FREITAZ'),
  ('Pietro', 'PIETRO'),
  ('Plaster', 'PLASTER'),
  ('Paltrinieri', 'PALTRINIERI'),
  ('Sakai', 'SAKAI'),
  ('Worvis', 'WORVIS'),
  ('Victor', 'VICTOR')
on conflict (coupon_code) do nothing;
